project:
  type: book
  output-dir: docs

book:
  title: "Oline Learning Diary"
  author: "Zhenghao Weng"
  date: "2024/3/12"
  chapters:
    - index.qmd
    - week1_Introduction.qmd
    - week2_Xaringan.qmd
    - week3_Correction.qmd
    - week4_Policy.qmd
    - week6_GEE.qmd
    - week7_Classification1.qmd
    - week8_Classification2.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

